language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

script: "./gradlew clean build"

deploy:
  provider: releases
  api_key: "$GH_KEY"
  file:
      - "app/build/outputs/apk/moledroid-debug.apk"
  skip_cleanup: true
  on:
    branch: master
    tags: true